version: '3'
services:
  postgres:
    image: postgres:15.2
    env_file:
      - ./movies_admin/config/.env
    volumes:
      - movies_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d movies_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  service:
    build: ./movies_admin
    depends_on:
      - postgres
    volumes:
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    environment:
      DEBUG: 'False'
    env_file:
      - ./movies_admin/config/.env

  nginx:
    image: nginx:1.22.1
    volumes:
      - ./movies_admin/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_admin/src:/etc/nginx/conf.d:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - service
    ports:
      - '80:80'

volumes:
  movies_postgres_data:
  static_value:
  media_value: